### PR TITLE
#trivial Fix new line 

### PR DESCRIPTION
**Pull request by JosephSalomon**
Needed to fix the new line, had to add a function to split it and changed single quotes to double. Also added "\r" so it works universally on unix and windows.  
Problem #104 solved

### CODE REVIEW

**Comment by Huddie** [comment]
@JosephSalomon did you create that function or it’s built in? 
Also what’s \r? 
Also why \r and \n do they do separate things?

**Comment by Huddie** [comment]
You mentioned both #103 and #104 I only see changes for 1 of those. Is that correct?

**Comment by JosephSalomon** [comment]
@Huddie 
The function is built in. 
"\r\n" is for universal new line whereas "\n" is just for unix

I also meant to write only #104, that should be fixed

**Comment by Huddie** [comment]
@JosephSalomon Sick! i never knew about \r\n but deff necessary. Good find. 
Have you tested locally?

**Comment by JosephSalomon** [comment]
Yes I have!

**Comment by Huddie** [comment]
@JosephSalomon looks good on my side, my one issue is you have apart of the PR your last PR. commit 9baf2c4 isnt apart of this PR. Can you clean that out?

**Pull request closed without merging**
